version: '3'

services:
  web:
    image: subconverter-react
    build:
      context: .
    ports:
      - '80:80'
    volumes:
      - nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    image: tindy2013/subconverter:latest
